import { expect } from "chai";
import AssSubtitles from "@/utils/AssSubtitles";

const subtitlesFile = `[Script Info]
; Script generated by FFmpeg/Lavc58.91.100
ScriptType: v4.00+
PlayResX: 384
PlayResY: 288
ScaledBorderAndShadow: yes

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,Arial,16,&Hffffff,&Hffffff,&H0,&H0,0,0,0,0,100,100,0,0,1,1,0,2,10,10,10,0

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 0,0:00:04.02,0:00:10.68,Default,,0,0,0,,Hello world
Dialogue: 0,0:00:10.68,0:00:15.66,Default,,0,0,0,,This is a test\\Nwith a new line
Dialogue: 0,0:00:15.90,0:00:18.95,Default,,0,0,0,,This is the 3rd subtitle line`;

describe("AssSubtitles", () => {
  it("should convert .ass subtitles to captions", () => {
    const captions = AssSubtitles.convertAssToCaptions(subtitlesFile);

    expect(captions).to.exist;

    expect(captions![0].text).to.be.equal("Hello world");
    expect(captions![1].text).to.be.equal("This is a test\nwith a new line");
    expect(captions![2].text).to.be.equal("This is the 3rd subtitle line");

    expect(captions![0].startTime).to.be.equal(4.02);
    expect(captions![1].startTime).to.be.equal(10.68);
    expect(captions![2].startTime).to.be.equal(15.9);

    expect(captions![0].endTime).to.be.equal(10.68);
    expect(captions![1].endTime).to.be.equal(15.66);
    expect(captions![2].endTime).to.be.equal(18.95);
  });
});
